# Generated by Django 3.1 on 2020-08-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0002_auto_20200206_0053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumImage',
        ),
    ]
