# Generated by Django 3.1 on 2020-08-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0004_slides'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slides',
            new_name='Slide',
        ),
    ]
